name: Show Secret Password Demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Password via python script
      run: python test.py ${{secrets.PROD_PASSWORD}}
