name: Show Secret Password Demo

on:
  workflow_dispatch:

jobs:
  build_prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Print Password via Python script
      env:
        PROD_PASSWORD: ${{ secrets.PROD_PASSWORD }}
      run: python test.py $PROD_PASSWORD
