name: Build oXygen Plugin

on:
  workflow_dispatch:

jobs:
  build_prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Inject encrypted password via Python script
      env:
        PROD_PASSWORD: ${{ secrets.PROD_PASSWORD }}
      run: python obfuscate.py $PROD_PASSWORD
