name: Show Secret Password Demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Print Password via Python script
      run: python test.py ${{secrets.PROD_PASSWORD}}
